### ISSUE TITLE
Incorrect Death Bank/Pile tracking

### ISSUE THREAD

**Issue by Nick2bad4u** [Thource/dude-wheres-my-stuff#150]
[Here is an example of what I'm talking about](https://i.gyazo.com/8d79dd3989500e4e84072af879f3f9b5.png)

![image](https://github.com/Thource/dude-wheres-my-stuff/assets/20943337/0fe6ca4f-5890-4c36-9e00-4767d192fa9e)

**Comment by Thource** [comment]
Could you send a screenshot of your plugin panel with the death storages tab selected please?

**Comment by Nick2bad4u** [comment]
> Could you send a screenshot of your plugin panel with the death storages tab selected please?

[Death Storage Panel](https://gyazo.com/49cb1ed6d7cf2990af0e9fb4480bca1a)

I have not done Zulrah in about 3 years since I did my 5500 kc lol.

[Also, its no longer showing me an infobox.](https://gyazo.com/003b948526d35a0d1b590a727bb99d29)

Am I supposed to be manually deleting these death banks?

**Comment by Thource** [comment]
It’s personal preference if you want to delete the lost deathbanks or not (by right clicking them), they won’t cause any issues if you do want to keep them around.

Did the infobox disappear randomly or did you die again?

**Comment by Nick2bad4u** [comment]
> It’s personal preference if you want to delete the lost deathbanks or not (by right clicking them), they won’t cause any issues if you do want to keep them around.
> 
> Did the infobox disappear randomly or did you die again?

You know I might have figured out the issue.

This seems to happen only?? when you try to loot a grave and you dont have enough space to fully loot the grave.

It appears that the items that don't get looted at first - end up as a "death bank zulrah"

**Comment by Thource** [comment]
You are 100% right, thank you so much for figuring this out, it's so obscure that I literally wouldn't even have considered trying it.

**Comment by Nick2bad4u** [comment]
> You are 100% right, thank you so much for figuring this out, it's so obscure that I literally wouldn't even have considered trying it.

Glad I was able to help.

Honestly, it took me about 5-6 deaths and this happened before I could pinpoint the cause.

I wouldn't have even checked the death bank tab without ur suggestions from earlier so, well done to us both.

I had a kinda Eureka! moment when I realized the exact items left in my grave were the death bank items.
