### ISSUE TITLE
Feature Request: Item count tooltips

### ISSUE THREAD

**Issue by Fiffers** [Thource/dude-wheres-my-stuff#161]
It'd be pretty useful to be able to hover over an item in your inventory and be able to see how many of that item remain in your bank or other storage. I submitted a PR for a feature like this on another plugin, but it's been waiting to be reviewed for over a year and I've lost hope of it ever being merged.

Anyways, here's what it looks like in action:
![image](https://github.com/Thource/dude-wheres-my-stuff/assets/14336807/252e2e6c-5ce2-4c3b-a2a0-3ecc2846cc96)

**Comment by Thource** [comment]
Great idea, thanks!

**Comment by Thource** [comment]
![image](https://github.com/Thource/dude-wheres-my-stuff/assets/4104309/bd148e88-6706-40e8-bec8-4636e48680ee)

![image](https://github.com/Thource/dude-wheres-my-stuff/assets/4104309/2e17349b-c3eb-487d-a9d3-c0ee54adb0a4)

**Comment by Fiffers** [comment]
That's perfect! Can't wait to get the update =)
