### ISSUE TITLE
Minigame storage: Volcanic mine

### ISSUE THREAD

**Issue by ingmarins** [Thource/dude-wheres-my-stuff#189]
It would be nice to see how many points I have in Volcanic mine.

**Comment by jammy-dodgers** [comment]
![image](https://github.com/Thource/dude-wheres-my-stuff/assets/16457802/9896a07a-c5b1-470b-87e3-59fe3dd9a23a)

VarPlayer 261

Upon leaving the mine after gaining points, no VarPlayer update is reported until the petrified pete's shop UI is checked again

![image](https://github.com/Thource/dude-wheres-my-stuff/assets/16457802/e4d92acd-0431-4f66-b071-c181921584e1)
