### ISSUE TITLE
[Bug] Both Varrock STASH units overwrite each other.

### ISSUE THREAD

**Issue by jeremybahadirli** [Thource/dude-wheres-my-stuff#204]
There are two STASH units in Varrock: one outside Gypsy tent, and one outside Thessalia's clothes shop, respectively named in the plugin: "Gypsy Aris' tent" and "Iffie Nitter in Varrock".

When checking both of these STASH units, both entries in the plugin do not become filled. When checking the second STASH unit, that one becomes filled, but the other Varrock STASH unit entry will then become empty, even if it is filled in-game.

Example:
1. Both STASH units are empty.
2. You fill the Gypsy tent unit.
    - The "Gypsy Aris' tent" entry in the plugin shows the items as stored.
3. You then fill the clothes shop unit.
    - The "Iffie Nitter in Varrock" entry shows the items as stored.
    - Simultaneously, the "Gypsy Aris' tent" entry erroneously becomes empty, even though it still contains the items stored in step 2.

**Comment by Thource** [comment]
To determine which stash unit you're using, I check if you are less than 10 tiles away from it, these units must be within 10 of each other. It's an easy fix, I'll just reduce the range
