### ISSUE TITLE
Deathpiles do not recognize when "always empty seed boxes on death" is turned off

### ISSUE THREAD

**Issue by nick10909** [Thource/dude-wheres-my-stuff#208]
I have "Always empty seed boxes on death" turned off, and whenever I make a deathpile with the seedbox, the plugin thinks that the seeds inside the box will go into the pile. Thus, when I pick up all the items, the plugin thinks there are still some seeds remaining in the pile, and does not remove the pile automatically. This may also apply to the other "always empty ___" options in the OSRS gameplay settings, aside from rune pouch.

**Comment by Thource** [comment]
Thanks for reporting this, I've already got a fix waiting to go and will hopefully be making a new release soon
