### ISSUE TITLE
Carryable storage - Forestry kit

### ISSUE THREAD

**Issue by Thource** [Thource/dude-wheres-my-stuff#223]
This should also be populated by Forestry basket

**Comment by jammy-dodgers** [comment]
![image](https://github.com/Thource/dude-wheres-my-stuff/assets/16457802/878da4c0-135b-4b2f-927b-ac50f93addd2)
FYI: Standard forestry kit

**Comment by jammy-dodgers** [comment]
https://github.com/Thource/dude-wheres-my-stuff/assets/16457802/628a9fc8-c187-4a4a-921b-8b623701ed49

While it can't detect the leaves going into the kit, there is a game message for it.
![image](https://github.com/Thource/dude-wheres-my-stuff/assets/16457802/0ea632c9-6b91-4fb9-8086-83b34ae23470)

**Comment by jammy-dodgers** [comment]
Using items on the kit / emptying the kit in the UI produces no game messages
