### ISSUE TITLE
Dying (but not wiping) at Theatre of Blood incorrectly creates a deathbank

### ISSUE THREAD

**Issue by Nightfirecat** [Thource/dude-wheres-my-stuff#302]

**Comment by Thource** [comment]
Fix is ready, waiting for plugin hub approval 

https://github.com/runelite/plugin-hub/pull/6252

https://github.com/Thource/dude-wheres-my-stuff/issues/82

**Comment by Nightfirecat** [comment]
Ah, apologies for the duplicate then. Thanks!
