### ISSUE TITLE
Conflicts with Monster HP Percentage Plugin

### ISSUE THREAD

**Issue by AbusiveTuna** [Thource/dude-wheres-my-stuff#47]
Not technically your issue so feel free to close this right away, but thought I'd let you know. 

Currently something conflicts between dude wheres my stuff? and https://github.com/lejeffe/MonsterHP

Multiple users with both plugins had monster hp percent stuck at 100%, uninstalling this plugin made it work again. 

Again not your issue to fix since they're both plugin-hub plugins, but thought it might help to know anyway.

**Comment by AbusiveTuna** [comment]
This issue started to pop up around the time of your Septemeber 8th commits, but I really don't see what can be causing the conflict from those changes unless the POH death changes are somehow effecting how monster HP percentage deals with regions.

**Comment by Thource** [comment]
Fixed by https://github.com/lejeffe/MonsterHP/pull/18
